// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://copprrcbucmhlmxsxfzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvcHBycmNidWNtaGxteHN4ZnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMDM1OTYsImV4cCI6MjA1ODg3OTU5Nn0.AsmTv-a6TROGJwK9L4-Tm2333j89riEU8TBoEMd3U6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);